name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/github-script@v5
      id: set-result
      with:
        script: return "Hello!"
        result-encoding: string
    - name: Get result
      run: echo "${{steps.set-result.outputs.result}}"
