name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: ./configure.sh
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: sudo apt-get update -y
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
